title: Ryan Chen Zhang
description: 8th-grade student at T.H. Rogers School of Houston
#show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
# Author Information
author:
  name: "Ryan Chen Zhang"
  avatar: "/images/avatar.jpg"  # Path to the avatar image
  #bio: "A brief bio about yourself."
